[package]
name = "serde_json_tests"
version = "0.7.1"
authors = ["Erick Tryzelaar <erick.tryzelaar@gmail.com>"]
build = "build.rs"

[features]
default = ["serde_macros"]
with-syntex = ["syntex", "serde_codegen", "indoc/with-syntex"]
nightly-testing = ["clippy", "serde_json/clippy"]

[build-dependencies]
indoc = "*"
serde_codegen = { version = "*", optional = true }
skeptic = "^0.4.0"
syntex = { version = "*", optional = true }

[dependencies]
clippy = { version = "^0.*", optional = true }
indoc = "*"
num-traits = "*"
rustc-serialize = "*"
#serde = "*"
serde = { path = "../../serde/serde" }
serde_json = { version = "*", path = "../json" }
#serde_macros = { version = "*", optional = true }
serde_macros = { path = "../../serde/serde_macros", optional = true }
skeptic = "^0.4.0"

[dev-dependencies]
decimal = "*"

[[test]]
name = "test"
path = "tests/test.rs"

[[bench]]
name = "bench"
path = "benches/bench.rs"
